// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSpell(arg1) {
  return window['go']['main']['App']['AddSpell'](arg1);
}

export function BeginUpgrade(arg1) {
  return window['go']['main']['App']['BeginUpgrade'](arg1);
}

export function BrowseEQDirectory() {
  return window['go']['main']['App']['BrowseEQDirectory']();
}

export function CreateTrigger(arg1, arg2) {
  return window['go']['main']['App']['CreateTrigger'](arg1, arg2);
}

export function CreateTriggerGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateTriggerGroup'](arg1, arg2);
}

export function DeleteTrigger(arg1) {
  return window['go']['main']['App']['DeleteTrigger'](arg1);
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetAutomations() {
  return window['go']['main']['App']['GetAutomations']();
}

export function GetAvailableUpdate() {
  return window['go']['main']['App']['GetAvailableUpdate']();
}

export function GetBatphones() {
  return window['go']['main']['App']['GetBatphones']();
}

export function GetCharClassWithInference(arg1, arg2) {
  return window['go']['main']['App']['GetCharClassWithInference'](arg1, arg2);
}

export function GetCharContent(arg1) {
  return window['go']['main']['App']['GetCharContent'](arg1);
}

export function GetCharInfos(arg1) {
  return window['go']['main']['App']['GetCharInfos'](arg1);
}

export function GetCharInventory(arg1) {
  return window['go']['main']['App']['GetCharInventory'](arg1);
}

export function GetCharNames(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCharNames'](arg1, arg2, arg3);
}

export function GetCharSpellbook(arg1) {
  return window['go']['main']['App']['GetCharSpellbook'](arg1);
}

export function GetCharTable(arg1, arg2) {
  return window['go']['main']['App']['GetCharTable'](arg1, arg2);
}

export function GetCharacterName() {
  return window['go']['main']['App']['GetCharacterName']();
}

export function GetClientActivity() {
  return window['go']['main']['App']['GetClientActivity']();
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetCurrentZone() {
  return window['go']['main']['App']['GetCurrentZone']();
}

export function GetGameClock() {
  return window['go']['main']['App']['GetGameClock']();
}

export function GetGuildMapPositions(arg1) {
  return window['go']['main']['App']['GetGuildMapPositions'](arg1);
}

export function GetIniSettings() {
  return window['go']['main']['App']['GetIniSettings']();
}

export function GetMobHPs() {
  return window['go']['main']['App']['GetMobHPs']();
}

export function GetPlayerPosition() {
  return window['go']['main']['App']['GetPlayerPosition']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSpellsForClass(arg1) {
  return window['go']['main']['App']['GetSpellsForClass'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTimers() {
  return window['go']['main']['App']['GetTimers']();
}

export function GetToonIdentities() {
  return window['go']['main']['App']['GetToonIdentities']();
}

export function GetTriggerState() {
  return window['go']['main']['App']['GetTriggerState']();
}

export function GetTriggerTree() {
  return window['go']['main']['App']['GetTriggerTree']();
}

export function GetZoneInfo() {
  return window['go']['main']['App']['GetZoneInfo']();
}

export function GetZones() {
  return window['go']['main']['App']['GetZones']();
}

export function ImportGINATriggers() {
  return window['go']['main']['App']['ImportGINATriggers']();
}

export function IsAdminMode() {
  return window['go']['main']['App']['IsAdminMode']();
}

export function IsBotToon(arg1) {
  return window['go']['main']['App']['IsBotToon'](arg1);
}

export function IsFilteredToon(arg1) {
  return window['go']['main']['App']['IsFilteredToon'](arg1);
}

export function IsLinked() {
  return window['go']['main']['App']['IsLinked']();
}

export function IsOfficer() {
  return window['go']['main']['App']['IsOfficer']();
}

export function IsUpgrading() {
  return window['go']['main']['App']['IsUpgrading']();
}

export function OpenMap() {
  return window['go']['main']['App']['OpenMap']();
}

export function PollLinking(arg1) {
  return window['go']['main']['App']['PollLinking'](arg1);
}

export function RefreshCharInfos(arg1) {
  return window['go']['main']['App']['RefreshCharInfos'](arg1);
}

export function RenameTriggerGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameTriggerGroup'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTrigger(arg1) {
  return window['go']['main']['App']['SaveTrigger'](arg1);
}

export function ScrapeSpellPreview(arg1) {
  return window['go']['main']['App']['ScrapeSpellPreview'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetAutomations(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAutomations'](arg1, arg2, arg3);
}

export function SetClientMuted(arg1, arg2) {
  return window['go']['main']['App']['SetClientMuted'](arg1, arg2);
}

export function SetFilteredToons(arg1, arg2) {
  return window['go']['main']['App']['SetFilteredToons'](arg1, arg2);
}

export function SetTriggerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetTriggerEnabled'](arg1, arg2);
}

export function SetTriggerGroupEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetTriggerGroupEnabled'](arg1, arg2);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function StartLinking() {
  return window['go']['main']['App']['StartLinking']();
}

export function StartMapStrobe() {
  return window['go']['main']['App']['StartMapStrobe']();
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}

export function ToggleFilteredToon(arg1) {
  return window['go']['main']['App']['ToggleFilteredToon'](arg1);
}

export function Unlink() {
  return window['go']['main']['App']['Unlink']();
}
