// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BeginUpgrade(arg1:string):Promise<void>;

export function BrowseEQDirectory():Promise<string>;

export function GetAutoStart():Promise<boolean>;

export function GetCharClassWithInference(arg1:string,arg2:Array<string>):Promise<string>;

export function GetCharContent(arg1:string):Promise<string>;

export function GetCharInfos(arg1:Array<string>):Promise<Record<string, main.CharInfo>>;

export function GetCharInventory(arg1:string):Promise<Array<main.InventoryItem>>;

export function GetCharNames(arg1:string,arg2:boolean,arg3:boolean):Promise<Array<main.CharEntry>>;

export function GetCharSpellbook(arg1:string):Promise<Array<string>>;

export function GetCharacterName():Promise<string>;

export function GetClientActivity():Promise<Array<string>>;

export function GetClients():Promise<Array<main.wailsClientEntry>>;

export function GetCurrentZone():Promise<string>;

export function GetGuildMapPositions(arg1:string):Promise<Array<main.MapPosition>>;

export function GetPlayerPosition():Promise<main.PlayerPosition>;

export function GetSettings():Promise<main.Settings>;

export function GetSpellsForClass(arg1:string):Promise<Array<main.SpellEntry>>;

export function GetStatus():Promise<main.StatusSnapshot>;

export function GetTimers():Promise<main.TimersData>;

export function GetToonIdentities():Promise<Record<string, string>>;

export function GetZoneInfo():Promise<Array<main.ZoneNick>>;

export function GetZones():Promise<Array<main.wailsZoneData>>;

export function IsAdminMode():Promise<boolean>;

export function IsBotToon(arg1:string):Promise<boolean>;

export function IsFilteredToon(arg1:string):Promise<boolean>;

export function IsLinked():Promise<boolean>;

export function IsUpgrading():Promise<boolean>;

export function PollLinking(arg1:string):Promise<boolean>;

export function RefreshCharInfos(arg1:Array<string>):Promise<Record<string, main.CharInfo>>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function Show():Promise<void>;

export function StartLinking():Promise<string>;

export function ToggleFilteredToon(arg1:string):Promise<void>;

export function Unlink():Promise<void>;
