// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseEQDirectory():Promise<string>;

export function GetAutoStart():Promise<boolean>;

export function GetCharContent(arg1:string):Promise<string>;

export function GetCharNames(arg1:boolean,arg2:boolean):Promise<Array<string>>;

export function GetClients():Promise<Array<main.adminClientEntry>>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<main.StatusSnapshot>;

export function GetZones():Promise<Array<main.zoneData>>;

export function IsAdminMode():Promise<boolean>;

export function IsBotToon(arg1:string):Promise<boolean>;

export function IsFilteredToon(arg1:string):Promise<boolean>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function Show():Promise<void>;

export function ToggleFilteredToon(arg1:string):Promise<void>;
